# -*- coding: utf-8 -*-
"""Captcha Cracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pdCjLWGTOiEldTXUEHYmN3AMg91-Myol
"""

#captcha_cracker
from random import *
user_captcha= input("Enter Captcha")
captcha= ['a','b','c','d', 'e', 'f', 'g', 'h', 'i', 'j','k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
guess=''

while(guess!=user_captcha):
  guess=''
  for letter in range(len(user_captcha)):
    guess_letter= captcha[randint(0,61)]
    guess=str(guess_letter)+str(guess)
    print(guess)
    print()